//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  importantDates: ImportantDates;
  importantDatesConnection: ImportantDatesConnection;
  speakers: Speakers;
  speakersConnection: SpeakersConnection;
  committee: Committee;
  committeeConnection: CommitteeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryImportantDatesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryImportantDatesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ImportantDatesFilter>;
};


export type QuerySpeakersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySpeakersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpeakersFilter>;
};


export type QueryCommitteeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCommitteeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CommitteeFilter>;
};

export type DocumentFilter = {
  importantDates?: InputMaybe<ImportantDatesFilter>;
  speakers?: InputMaybe<SpeakersFilter>;
  committee?: InputMaybe<CommitteeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = ImportantDates | Speakers | Committee | Folder;

export type ImportantDatesRoot = {
  __typename?: 'ImportantDatesRoot';
  event: Scalars['String']['output'];
  date: Scalars['String']['output'];
  status?: Maybe<Scalars['String']['output']>;
};

export type ImportantDates = Node & Document & {
  __typename?: 'ImportantDates';
  root?: Maybe<Array<Maybe<ImportantDatesRoot>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImportantDatesRootFilter = {
  event?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
};

export type ImportantDatesFilter = {
  root?: InputMaybe<ImportantDatesRootFilter>;
};

export type ImportantDatesConnectionEdges = {
  __typename?: 'ImportantDatesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ImportantDates>;
};

export type ImportantDatesConnection = Connection & {
  __typename?: 'ImportantDatesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ImportantDatesConnectionEdges>>>;
};

export type SpeakersRootPhoto = {
  __typename?: 'SpeakersRootPhoto';
  url?: Maybe<Scalars['String']['output']>;
  file?: Maybe<Scalars['String']['output']>;
};

export type SpeakersRoot = {
  __typename?: 'SpeakersRoot';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  affiliation?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<SpeakersRootPhoto>;
  topic?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
};

export type Speakers = Node & Document & {
  __typename?: 'Speakers';
  root?: Maybe<Array<Maybe<SpeakersRoot>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SpeakersRootPhotoFilter = {
  url?: InputMaybe<StringFilter>;
  file?: InputMaybe<ImageFilter>;
};

export type SpeakersRootFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  affiliation?: InputMaybe<StringFilter>;
  photo?: InputMaybe<SpeakersRootPhotoFilter>;
  topic?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type SpeakersFilter = {
  root?: InputMaybe<SpeakersRootFilter>;
};

export type SpeakersConnectionEdges = {
  __typename?: 'SpeakersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Speakers>;
};

export type SpeakersConnection = Connection & {
  __typename?: 'SpeakersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SpeakersConnectionEdges>>>;
};

export type CommitteeRootMembersPhoto = {
  __typename?: 'CommitteeRootMembersPhoto';
  url?: Maybe<Scalars['String']['output']>;
  file?: Maybe<Scalars['String']['output']>;
};

export type CommitteeRootMembers = {
  __typename?: 'CommitteeRootMembers';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  affiliation?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<CommitteeRootMembersPhoto>;
};

export type CommitteeRoot = {
  __typename?: 'CommitteeRoot';
  id: Scalars['String']['output'];
  label: Scalars['String']['output'];
  members?: Maybe<Array<Maybe<CommitteeRootMembers>>>;
};

export type Committee = Node & Document & {
  __typename?: 'Committee';
  root?: Maybe<Array<Maybe<CommitteeRoot>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CommitteeRootMembersPhotoFilter = {
  url?: InputMaybe<StringFilter>;
  file?: InputMaybe<ImageFilter>;
};

export type CommitteeRootMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  affiliation?: InputMaybe<StringFilter>;
  photo?: InputMaybe<CommitteeRootMembersPhotoFilter>;
};

export type CommitteeRootFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  members?: InputMaybe<CommitteeRootMembersFilter>;
};

export type CommitteeFilter = {
  root?: InputMaybe<CommitteeRootFilter>;
};

export type CommitteeConnectionEdges = {
  __typename?: 'CommitteeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Committee>;
};

export type CommitteeConnection = Connection & {
  __typename?: 'CommitteeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CommitteeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateImportantDates: ImportantDates;
  createImportantDates: ImportantDates;
  updateSpeakers: Speakers;
  createSpeakers: Speakers;
  updateCommittee: Committee;
  createCommittee: Committee;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateImportantDatesArgs = {
  relativePath: Scalars['String']['input'];
  params: ImportantDatesMutation;
};


export type MutationCreateImportantDatesArgs = {
  relativePath: Scalars['String']['input'];
  params: ImportantDatesMutation;
};


export type MutationUpdateSpeakersArgs = {
  relativePath: Scalars['String']['input'];
  params: SpeakersMutation;
};


export type MutationCreateSpeakersArgs = {
  relativePath: Scalars['String']['input'];
  params: SpeakersMutation;
};


export type MutationUpdateCommitteeArgs = {
  relativePath: Scalars['String']['input'];
  params: CommitteeMutation;
};


export type MutationCreateCommitteeArgs = {
  relativePath: Scalars['String']['input'];
  params: CommitteeMutation;
};

export type DocumentUpdateMutation = {
  importantDates?: InputMaybe<ImportantDatesMutation>;
  speakers?: InputMaybe<SpeakersMutation>;
  committee?: InputMaybe<CommitteeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  importantDates?: InputMaybe<ImportantDatesMutation>;
  speakers?: InputMaybe<SpeakersMutation>;
  committee?: InputMaybe<CommitteeMutation>;
};

export type ImportantDatesRootMutation = {
  event?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
};

export type ImportantDatesMutation = {
  root?: InputMaybe<Array<InputMaybe<ImportantDatesRootMutation>>>;
};

export type SpeakersRootPhotoMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  file?: InputMaybe<Scalars['String']['input']>;
};

export type SpeakersRootMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  affiliation?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<SpeakersRootPhotoMutation>;
  topic?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type SpeakersMutation = {
  root?: InputMaybe<Array<InputMaybe<SpeakersRootMutation>>>;
};

export type CommitteeRootMembersPhotoMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  file?: InputMaybe<Scalars['String']['input']>;
};

export type CommitteeRootMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  affiliation?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<CommitteeRootMembersPhotoMutation>;
};

export type CommitteeRootMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  members?: InputMaybe<Array<InputMaybe<CommitteeRootMembersMutation>>>;
};

export type CommitteeMutation = {
  root?: InputMaybe<Array<InputMaybe<CommitteeRootMutation>>>;
};

export type ImportantDatesPartsFragment = { __typename: 'ImportantDates', root?: Array<{ __typename: 'ImportantDatesRoot', event: string, date: string, status?: string | null } | null> | null };

export type SpeakersPartsFragment = { __typename: 'Speakers', root?: Array<{ __typename: 'SpeakersRoot', name: string, role?: string | null, affiliation?: string | null, topic?: string | null, linkedin?: string | null, photo?: { __typename: 'SpeakersRootPhoto', url?: string | null, file?: string | null } | null } | null> | null };

export type CommitteePartsFragment = { __typename: 'Committee', root?: Array<{ __typename: 'CommitteeRoot', id: string, label: string, members?: Array<{ __typename: 'CommitteeRootMembers', name: string, role?: string | null, affiliation?: string | null, photo?: { __typename: 'CommitteeRootMembersPhoto', url?: string | null, file?: string | null } | null } | null> | null } | null> | null };

export type ImportantDatesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ImportantDatesQuery = { __typename?: 'Query', importantDates: { __typename: 'ImportantDates', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'ImportantDatesRoot', event: string, date: string, status?: string | null } | null> | null } };

export type ImportantDatesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ImportantDatesFilter>;
}>;


export type ImportantDatesConnectionQuery = { __typename?: 'Query', importantDatesConnection: { __typename?: 'ImportantDatesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ImportantDatesConnectionEdges', cursor: string, node?: { __typename: 'ImportantDates', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'ImportantDatesRoot', event: string, date: string, status?: string | null } | null> | null } | null } | null> | null } };

export type SpeakersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SpeakersQuery = { __typename?: 'Query', speakers: { __typename: 'Speakers', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'SpeakersRoot', name: string, role?: string | null, affiliation?: string | null, topic?: string | null, linkedin?: string | null, photo?: { __typename: 'SpeakersRootPhoto', url?: string | null, file?: string | null } | null } | null> | null } };

export type SpeakersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpeakersFilter>;
}>;


export type SpeakersConnectionQuery = { __typename?: 'Query', speakersConnection: { __typename?: 'SpeakersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SpeakersConnectionEdges', cursor: string, node?: { __typename: 'Speakers', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'SpeakersRoot', name: string, role?: string | null, affiliation?: string | null, topic?: string | null, linkedin?: string | null, photo?: { __typename: 'SpeakersRootPhoto', url?: string | null, file?: string | null } | null } | null> | null } | null } | null> | null } };

export type CommitteeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CommitteeQuery = { __typename?: 'Query', committee: { __typename: 'Committee', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'CommitteeRoot', id: string, label: string, members?: Array<{ __typename: 'CommitteeRootMembers', name: string, role?: string | null, affiliation?: string | null, photo?: { __typename: 'CommitteeRootMembersPhoto', url?: string | null, file?: string | null } | null } | null> | null } | null> | null } };

export type CommitteeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CommitteeFilter>;
}>;


export type CommitteeConnectionQuery = { __typename?: 'Query', committeeConnection: { __typename?: 'CommitteeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CommitteeConnectionEdges', cursor: string, node?: { __typename: 'Committee', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, root?: Array<{ __typename: 'CommitteeRoot', id: string, label: string, members?: Array<{ __typename: 'CommitteeRootMembers', name: string, role?: string | null, affiliation?: string | null, photo?: { __typename: 'CommitteeRootMembersPhoto', url?: string | null, file?: string | null } | null } | null> | null } | null> | null } | null } | null> | null } };

export const ImportantDatesPartsFragmentDoc = gql`
    fragment ImportantDatesParts on ImportantDates {
  __typename
  root {
    __typename
    event
    date
    status
  }
}
    `;
export const SpeakersPartsFragmentDoc = gql`
    fragment SpeakersParts on Speakers {
  __typename
  root {
    __typename
    name
    role
    affiliation
    photo {
      __typename
      url
      file
    }
    topic
    linkedin
  }
}
    `;
export const CommitteePartsFragmentDoc = gql`
    fragment CommitteeParts on Committee {
  __typename
  root {
    __typename
    id
    label
    members {
      __typename
      name
      role
      affiliation
      photo {
        __typename
        url
        file
      }
    }
  }
}
    `;
export const ImportantDatesDocument = gql`
    query importantDates($relativePath: String!) {
  importantDates(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ImportantDatesParts
  }
}
    ${ImportantDatesPartsFragmentDoc}`;
export const ImportantDatesConnectionDocument = gql`
    query importantDatesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ImportantDatesFilter) {
  importantDatesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ImportantDatesParts
      }
    }
  }
}
    ${ImportantDatesPartsFragmentDoc}`;
export const SpeakersDocument = gql`
    query speakers($relativePath: String!) {
  speakers(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SpeakersParts
  }
}
    ${SpeakersPartsFragmentDoc}`;
export const SpeakersConnectionDocument = gql`
    query speakersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SpeakersFilter) {
  speakersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SpeakersParts
      }
    }
  }
}
    ${SpeakersPartsFragmentDoc}`;
export const CommitteeDocument = gql`
    query committee($relativePath: String!) {
  committee(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CommitteeParts
  }
}
    ${CommitteePartsFragmentDoc}`;
export const CommitteeConnectionDocument = gql`
    query committeeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CommitteeFilter) {
  committeeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CommitteeParts
      }
    }
  }
}
    ${CommitteePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      importantDates(variables: ImportantDatesQueryVariables, options?: C): Promise<{data: ImportantDatesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImportantDatesQueryVariables, query: string}> {
        return requester<{data: ImportantDatesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImportantDatesQueryVariables, query: string}, ImportantDatesQueryVariables>(ImportantDatesDocument, variables, options);
      },
    importantDatesConnection(variables?: ImportantDatesConnectionQueryVariables, options?: C): Promise<{data: ImportantDatesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImportantDatesConnectionQueryVariables, query: string}> {
        return requester<{data: ImportantDatesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImportantDatesConnectionQueryVariables, query: string}, ImportantDatesConnectionQueryVariables>(ImportantDatesConnectionDocument, variables, options);
      },
    speakers(variables: SpeakersQueryVariables, options?: C): Promise<{data: SpeakersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakersQueryVariables, query: string}> {
        return requester<{data: SpeakersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakersQueryVariables, query: string}, SpeakersQueryVariables>(SpeakersDocument, variables, options);
      },
    speakersConnection(variables?: SpeakersConnectionQueryVariables, options?: C): Promise<{data: SpeakersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakersConnectionQueryVariables, query: string}> {
        return requester<{data: SpeakersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpeakersConnectionQueryVariables, query: string}, SpeakersConnectionQueryVariables>(SpeakersConnectionDocument, variables, options);
      },
    committee(variables: CommitteeQueryVariables, options?: C): Promise<{data: CommitteeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CommitteeQueryVariables, query: string}> {
        return requester<{data: CommitteeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CommitteeQueryVariables, query: string}, CommitteeQueryVariables>(CommitteeDocument, variables, options);
      },
    committeeConnection(variables?: CommitteeConnectionQueryVariables, options?: C): Promise<{data: CommitteeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CommitteeConnectionQueryVariables, query: string}> {
        return requester<{data: CommitteeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CommitteeConnectionQueryVariables, query: string}, CommitteeConnectionQueryVariables>(CommitteeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.0/content/a35055d7-64c4-4928-ace0-edc5a7b4d2cb/github/development",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  